spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        user_sql_cooments: true

    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hiberante:
        SQL: debug